export enum ScreenNames {
  LOTTIE = "LOTTIE",
  GESTURE_HANDLER_TOUCHABLE = "GESTURE_HANDLER_TOUCHABLE",
  REACT_NATIVE_TOUCHABLE = "RN_TOUCHABLE",
  DYNAMIC_CHILDREN = "DYNAMIC_CHILDREN",
  INSTANT_ROOT = "INSTANT_ROOT",
}

export enum StackNames {
  EXAMPLES = "EXAMPLES",
  EXAMPLES_STACK = "EXAMPLES_STACK",
}
