export enum ScreenNames {
  GESTURE_HANDLER_TOUCHABLE = "GESTURE_HANDLER_TOUCHABLE",
  REACT_NATIVE_TOUCHABLE = "RN_TOUCHABLE",
  DYNAMIC_CHILDREN = "DYNAMIC_CHILDREN",
  INSTANT_ROOT = "INSTANT_ROOT",
  HOOKS = "HOOKS",
  FLEXIBLE_STYLES = "FLEXIBLE_STYLES",
  BOTTOM_SHEET = "BOTTOM_SHEET",
  MESSENGER = "MESSENGER",
  PORTAL_BEFORE_HOST = "PORTAL_BEFORE_HOST",
  INSTAGRAM_FEED = "INSTAGRAM_FEED",
  INSTAGRAM_REELS = "INSTAGRAM_REELS",
  NAVIGATION_LIFECYCLE = "NAVIGATION_LIFECYCLE",
  NAVIGATION_LIFECYCLE_NESTED = "NAVIGATION_LIFECYCLE_NESTED",
  TRAVEL_EXPLORE = "TRAVEL_EXPLORE",
  TRAVEL_DETAILS = "TRAVEL_DETAILS",
}

export enum StackNames {
  EXAMPLES = "EXAMPLES",
  EXAMPLES_STACK = "EXAMPLES_STACK",
}
